name: tadka-cms-app

services:
  # Backend - Docker Web Service
  - name: tadka-backend
    source_dir: /backend
    dockerfile_path: backend/Dockerfile
    github:
      repo: YOUR_GITHUB_USERNAME/tadka-cms
      branch: main
    http_port: 8000
    environment_slug: docker
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: MONGO_URL
        value: "mongodb+srv://doadmin:U3p18Bi6o542Z9uF@primepixel-mongodb-76909177.mongo.ondigitalocean.com/admin?retryWrites=true&w=majority"
      - key: DB_NAME
        value: tadka_cms
      - key: CORS_ORIGINS
        value: ${CORS_ORIGINS}
      - key: JWT_SECRET_KEY
        value: ${JWT_SECRET_KEY}
      - key: FRONTEND_URL
        value: ${FRONTEND_URL}
      - key: AWS_ACCESS_KEY_ID
        value: ${AWS_ACCESS_KEY_ID}
      - key: AWS_SECRET_ACCESS_KEY
        value: ${AWS_SECRET_ACCESS_KEY}
      - key: AWS_REGION
        value: ${AWS_REGION}
      - key: AWS_S3_BUCKET_NAME
        value: ${AWS_S3_BUCKET_NAME}
      - key: S3_ROOT_FOLDER
        value: ${S3_ROOT_FOLDER}
      - key: S3_MAX_FILE_SIZE
        value: "52428800"

# Frontend - Static Site
static_sites:
  - name: tadka-frontend
    source_dir: /frontend
    github:
      repo: YOUR_GITHUB_USERNAME/tadka-cms
      branch: main
    build_command: yarn build
    output_dir: build
    index_document: index.html
    error_document: index.html
    envs:
      - key: REACT_APP_BACKEND_URL
        scope: BUILD_TIME
        value: ${tadka-backend.PUBLIC_URL}
      - key: NODE_ENV
        scope: BUILD_TIME
        value: production
